my_first_int= 8
my_second_int= 12
Result= my_first_int + my_second_int
print(Result)
my_first_float= 23.8
my_second_float= 73.2
Result2= my_first_float + my_second_float
print(Result2)
my_first_string= "Este año "
my_second_string= "seré desarrollador de software" 
result3= my_first_string + my_second_string
print(f"El resultado de la oración es {result3}")
my_third_int= 12
my_list=[2,5,8,56]
my_list.extend([my_third_int])
print(my_list)
my_fourth_int= 57
my_third_float= 168.57
result4= my_fourth_int + my_third_float
print(result4)